# Generated by Django 3.1.2 on 2020-10-29 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201029_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='previous_choice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 18, 24, 18, 532738, tzinfo=utc), verbose_name='date end'),
        ),
    ]
